# Generated by Django 4.2.6 on 2023-10-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.IntegerField(default=0, verbose_name='чат ID пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='признак верификации'),
        ),
    ]
