# Generated by Django 4.2.6 on 2023-10-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время привычки')),
                ('action', models.CharField(max_length=200, verbose_name='действие')),
                ('is_nice_habbit', models.BooleanField(blank=True, default=False, null=True, verbose_name='приятная привычка')),
                ('periodicity', models.CharField(default='1', max_length=10, verbose_name='переодичность')),
                ('award', models.CharField(blank=True, max_length=100, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.TimeField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=True, verbose_name='признак публичности')),
                ('is_related_habbit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habbit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
