# Generated by Django 4.2.6 on 2023-10-29 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0002_habbit_last_executed_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habbit',
            new_name='Habit',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='is_nice_habbit',
            new_name='is_nice_habit',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='is_related_habbit',
            new_name='is_related_habit',
        ),
    ]
