# Generated by Django 4.2.6 on 2023-10-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_rename_habbit_habit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='last_executed_date',
        ),
    ]
